### ISSUE TITLE
menuhelper.choosecharacter should work for any controller

### ISSUE THREAD

**Issue by jhseu** [altf4/libmelee#16]
Right now it uses gamestate.ai_state, but there are cases where you want several bots on several controllers.

Probably the best fix is for the Controller class to record the port and control using gamestate.player[controller.port].

**Comment by altf4** [comment]
I'm not completely sure what you're saying? menuhelper.choosecharacter does work on any controller. You just have to set the port on command-line for your AI to change controller ports, like this:

`./example -p 3`

**Comment by jhseu** [comment]
I have multiple AI controllers in this case, so gamestate.opponent_state is also an AI controller.

It doesn't currently work in the case where both characters are AI controllers (like in reinforcement learning settings).

**Comment by jhseu** [comment]
To be specific, the code assumes exactly one AI controller because it assumes gamestate.ai_state is the only one controlled by AI.

**Comment by altf4** [comment]
Ahh, I see what you mean. Yea the code currently assumes that there's only one AI. 

In your opinion, would it be preferable to A) have libmelee have proper support for multiple AI's within the library? (Not assume that there's just one) Or B) would it be better to just run a separate instance of the AI, connected to the same dolphin?

You can run dolphin separately, then remove the line in example.py that spawns dolphin:
https://github.com/altf4/libmelee/blob/master/example.py#L73

I did this in SmashBot, and added a helper command-line parameter to toggle it on and off:
https://github.com/altf4/SmashBot/blob/master/smashbot.py#L75

There's an implementation issue currently with option B. libmelee receives gamestate info from a unix domain socket written to by dolphin. And this doesn't multiplex. So connecting to it from multiple processes won't work. I could possible create a multiplexor for the socket within libmelee so that option B works. 

I definitely would like to enable Melee AI tournaments in the future, so this sort of "head to head" is something I'd like to support. I personally feel like option B is best, so that AIs can treat each other as a black box and just play against whatever is on the other side, human or machine. But I'd appreciate input.

**Comment by altf4** [comment]
As a short-term workaround, you can set your AI to play against the in-game AI. It's obviously not as good for reinforcement learning, but it's something. And ought to get you results. I did this for a little while, but then I got sidetracked. :) I plan on coming back to making an ML SmashBot soon.

**Comment by jhseu** [comment]
I'd prefer A. It's pretty easy to make an interface supporting multiple bots with A if the user wrote the bot in Python.

I wrote an RL bot this weekend and multiple AIs (option A) already works for me outside of menuhelper. I just create another controller and pull the observations directly from gamestate.

**Comment by altf4** [comment]
This should be fixed now. I added a controller paramter to choosecharacter() so that you can specify who is doing the "choosing".
