### ISSUE TITLE
Expose button presses in libmelee API

### ISSUE THREAD

**Issue by jackeown** [altf4/libmelee#34]
I'm curious about writing a bot to play like a human. I would do this by playing many games and recording my inputs and making the bot "play like me" using supervised learning rather than reinforcement learning.

Is there an easy way to get controller inputs / actions from libmelee?

Thanks in advance,
Jack McKeown

**Comment by altf4** [comment]
So, libmelee isn't really equipped to read controller inputs. It can see what game actions were taken, and learn from that. But button presses are hard due to how the GameCube works. 

Button presses actually happen many times sub-frame (4x, iirc), and asynchronously. The game then polls the input once per frame. It's all extremely complex, and something that replay files somehow make work.

That said, I actually oriented libmelee's design such that it mimmic's the OpenAI gym interface a little. So as long as you're not relying on button presses super hard, it ought to work fine.

**Comment by altf4** [comment]
There isn't any reason libmelee COULDN'T see inputs in principle. But everything would have to change pretty dramatically.

**Comment by altf4** [comment]
After playing around with Slippi, this actually isn't as crazy or hard as I once thought. Might be worth adding.

**Comment by altf4** [comment]
Added in cc24ad133a9b027a439b6ee0cd1399fc1e54181a
