### ISSUE TITLE
SLP File support?

### ISSUE THREAD

**Issue by SaltyQuetzals** [altf4/libmelee#44]
The [console documentation](https://libmelee.readthedocs.io/en/latest/console.html) indicates that libmelee has yet to fully-support SLP files.
I was wondering what the current level of support is for SLP files. Can character positions (x/y) be retrieved with the current level of support?

**Comment by altf4** [comment]
Ah, I haven't gotten around to updating the docs yet. SLP file support is there! And yea, it definitely can see x,y character positions.

I don't have an example code for it just yet, so here's one:


```
console = melee.console.Console(is_dolphin=False, path=args.file)
console.connect()

while True:
    gamestate = console.step()
    if gamestate is None:
        break
    print(gamestate.player[1].x, gamestate.player[1].y)
```

step() will return None when the file ends. 

EDIT: Notably, no controller objects since you're just reading from file.

**Comment by SaltyQuetzals** [comment]
Also, are the `x`/`y` coordinates the character's location on the stage? Or their location on the screen (their pixel-based location)?

EDIT: Thank you for the rapid response, by the way!

**Comment by altf4** [comment]
x,y coords are the in-game locations measured in in-game units. So "on the stage" (Not on-screen locations)

**Comment by SaltyQuetzals** [comment]
Got it, thank you!
