### ISSUE TITLE
APM count

### ISSUE THREAD

**Issue by altf4** [altf4/libmelee#8]
Keep track of APM. Define what an "action" is in this context, too.

**Comment by ghost** [comment]
What is this for?
I ask because it could help in defining what to count as an _action_.
For example, dash dancing would drive crazy the counter.

There are some videos that try to do that in a manual way, they could be used as a reference:
https://www.youtube.com/watch?v=8vyBV94K4SE&list=PL6BPj6LYE4vpVf4H9BJWfBwrji9OJQAsz&index=2

**Comment by altf4** [comment]
It's just for fun. It's a cool little metric to show off. And I also don't quite know what an "action" means just yet. Would have to think about it.

**Comment by altf4** [comment]
Slippi has a good definition of APM for smash. Outlined in part here: http://www.meleeitonme.com/statistics-in-melee-p2/ Let's just use that

**Comment by altf4** [comment]
This isn't really something the API needs to have
